<?xml version="1.0" encoding="utf-8"?><Database Name="dc_Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=dc_Database;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dc_DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bc_group" Member="bc_group">
    <Type Name="bc_group">
      <Column Name="gid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="groupname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dc_article" Member="dc_article">
    <Type Name="dc_article">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="time_commit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="time_update" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="author" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="article_intro" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="article_context" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="article_tag_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dc_article_tag" Member="dc_article_tag">
    <Type Name="dc_article_tag">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="article_tag_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="article_tag_intro" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.dc_settings" Member="dc_settings">
    <Type Name="dc_settings">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="set_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="set_value" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="set_data" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.dc_user" Member="dc_user">
    <Type Name="dc_user">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="upassword" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nickname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="headimg" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="intro" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>