<?xml version="1.0" encoding="utf-8"?><Database Name="dc_Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=dc_Database;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dc_DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.dc_user" Member="dc_user">
    <Type Name="dc_user">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="upassword" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>